// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-wells.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function clientForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_wells_default = defineTool({
  name: "list_wells",
  title: "List wells",
  description: "List wells visible to the signed-in user (RLS-scoped by company). Supports optional state, formation, status filters and a limit.",
  inputSchema: {
    state: z.string().optional().describe("Filter by US state code, e.g. 'KS'."),
    formation: z.string().optional().describe("Filter by formation name."),
    status: z.string().optional().describe("Filter by well status."),
    limit: z.number().int().positive().max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ state, formation, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = clientForUser(ctx).from("wells").select(
      "id, api_number, well_name, operator, state, county, formation, status, latitude, longitude, total_depth, production_oil, production_gas, water_cut, spud_date, completion_date"
    ).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (state) query = query.eq("state", state);
    if (formation) query = query.eq("formation", formation);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, wells: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-well.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function clientForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_well_default = defineTool2({
  name: "get_well",
  title: "Get well",
  description: "Fetch a single well by API number or well UUID, including latest alerts and perforations.",
  inputSchema: {
    api_number: z2.string().optional().describe("10-digit API number."),
    well_id: z2.string().uuid().optional().describe("Well UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ api_number, well_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!api_number && !well_id) {
      return { content: [{ type: "text", text: "Provide api_number or well_id." }], isError: true };
    }
    const supabase = clientForUser2(ctx);
    let q = supabase.from("wells").select("*").limit(1);
    if (well_id) q = q.eq("id", well_id);
    else q = q.eq("api_number", api_number);
    const { data: wells, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const well = wells?.[0];
    if (!well) return { content: [{ type: "text", text: "Well not found" }], isError: true };
    const [{ data: alerts }, { data: perforations }] = await Promise.all([
      supabase.from("well_alerts").select("*").eq("well_id", well.id).order("created_at", { ascending: false }).limit(10),
      supabase.from("well_perforations").select("*").eq("well_id", well.id)
    ]);
    const payload = { well, alerts: alerts ?? [], perforations: perforations ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-knowledge.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function clientForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_knowledge_default = defineTool3({
  name: "search_knowledge",
  title: "Search AI Smart Well knowledge base",
  description: "Full-text search across the AI Smart Well knowledge base (9-stage pipeline, SPT, geology, petrophysics, economics).",
  inputSchema: {
    query: z3.string().min(1).describe("Natural-language search query."),
    limit: z3.number().int().positive().max(20).optional().describe("Max results (default 8).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await clientForUser3(ctx).rpc("search_sgom_knowledge", {
      q: query,
      match_count: limit ?? 8
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.94.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function clientForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_alerts_default = defineTool4({
  name: "list_alerts",
  title: "List well alerts",
  description: "Recent well alerts (production drops, water-cut exceedances, status changes) for the signed-in user's company.",
  inputSchema: {
    severity: z4.enum(["info", "warning", "critical"]).optional(),
    limit: z4.number().int().positive().max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ severity, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = clientForUser4(ctx).from("well_alerts").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (severity) q = q.eq("severity", severity);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rmfhcushsxkbgjnbawbs";
var mcp_default = defineMcp({
  name: "ai-smart-well-mcp",
  title: "AI Smart Well",
  version: "0.1.0",
  instructions: "Tools for the AI Smart Well oil & gas analytics platform. Query wells, alerts, and the knowledge base (9-stage pipeline, SPT patent US 8,863,823, geology, petrophysics, EOR). All queries are scoped to the signed-in user's company via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_wells_default, get_well_default, search_knowledge_default, list_alerts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
